spring:
  config:
    import: optional:configserver:http://localhost:8888/

  application:
    name : animal-service

  datasource:
    url: jdbc:h2:~/animal;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      jdbc:
        time_zone: UTC-3


